name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      # ADD THIS BLOCK ↓↓↓
      - name: Provide TF vars for CI (public key)
        run: |
          cat > ci.auto.tfvars <<'EOF'
          public_key = "${{ secrets.TF_PUBLIC_KEY }}"
          EOF

      - run: terraform fmt -check
      - run: terraform init -backend=false
      - run: terraform validate

  deploy-wp:
    runs-on: ubuntu-latest
    needs: terraform-validate
    steps:
      - uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Known hosts
        run: |
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Rsync changed files to EC2
        run: |
          rsync -az --delete \
            -e "ssh -p ${{ secrets.SSH_PORT }}" \
            --exclude 'wp-config.php' \
            --exclude 'wp-content/uploads/' \
            ./wordpress/ ${{ secrets.SSH_USER }}@${{ secrets.EC2_HOST }}:/var/www/html/
